version: '3.8'

services:
  web:
    build: .
    container_name: bank_rag_assistant
    ports:
      - "5001:5001"
    volumes:
      # Mount data directory for persistence
      - ./scraper/output:/app/scraper/output
      # Mount ChromaDB for persistent vector storage
      - ./chroma_db:/app/chroma_db
      # Mount .env for API keys
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
